"""Scoped provenance tests. Gateway outputs are test doubles, not GPU evidence."""
import copy
import json

import pytest

from runtime.asset_router import AssetRouter
from runtime.errors import WorkflowError
from runtime.geometry_acquisition import validate_geometry
from runtime.io import load_data, sha256
from runtime.planning import create_project, new_task
from runtime.manifest_manager import ManifestManager
from runtime.stage1_executor import Stage1Executor
from runtime.validators import validate_result
from tests.test_v02_geometry import ready, executor, request
from tests.test_v02_hy3d import gateway, generated_request
from tests.test_v02_planning import cli, ROOT


SOURCE = {'provider': 'hy3d', 'asset_id': 'tencent/Hunyuan3D-2.1',
          'original_url': 'https://huggingface.co/tencent/Hunyuan3D-2.1',
          'creator': 'Tencent Hunyuan3D-2.1 model; output generated by project operator',
          'license': 'hunyuan3d_21_community', 'license_verified': True,
          'attribution_required': True, 'modification_allowed': True}


def test_reachable_guide_example_matches_operational_policy():
    guide = (ROOT/'docs/hy3d-provenance.md').read_text()
    example = json.loads(guide.split('```json\n', 1)[1].split('```', 1)[0])
    assert example == SOURCE
    assert AssetRouter().legal({'source': example}, modification=True, generated_output=True)
    assert not AssetRouter().legal({'source': example}, modification=True)


def test_explicit_geometry_and_surface_retain_actual_provenance(tmp_path, glb_bytes):
    manager = ready(tmp_path)
    client, transport = gateway(glb_bytes)
    client.config['output_source'] = copy.deepcopy(SOURCE)
    result = executor(manager, client).run(generated_request())
    assert result['provenance'] == SOURCE
    assert validate_geometry(manager.root, result) == result
    assert manager.read()['geometry_assets']['machine']['versions'][0]['provenance'] == SOURCE
    assert manager.read()['geometry_assets']['machine']['status'] == 'review_required'
    assert len([call for call in transport.calls if call[0] == 'POST']) == 2
    assert cli('status', manager.root).returncode == 0
    # Later production revalidation must preserve the generated-route context.
    for name in ('platform', 'wall'):
        executor(manager).run(request(name, None, 'A'))
    manager.review_geometry('approved', expected_version=manager.read()['version'])
    from runtime.scene_production import PLAN_KINDS, prepare_scene, verify_packet
    documents = json.loads((ROOT/'tests/fixtures/v02/industrial_station.json').read_text())['documents']
    plans = {key: copy.deepcopy(documents[key]) for key in PLAN_KINDS}
    for obj in plans['blockout_plan']['objects']:
        obj.update(geometry_source='generated' if obj['object_id'] == 'machine' else 'library',
                   asset_id=obj['object_id'])
    for mapping in plans['semantic_material_map']['mappings']:
        mapping.update(slot='body', surface_source=None)
    manager.submit_scene_plans(plans, expected_version=manager.read()['version'])
    packet = prepare_scene(manager)
    assert verify_packet(packet['packet'], packet['sha256'])
    assert manager.read()['geometry_assets']['machine']['versions'][0]['provenance'] == SOURCE


def test_legacy_generated_delivery_retains_actual_license(tmp_path, glb_bytes, provider):
    task = new_task('machine', 'unique machine')
    task['search']['keywords'] = ['unique machine']
    task['hy3d'].update(enabled=True, mode='shape')
    task['routing']['preferred_route'] = 'hy3d_generate'
    root = tmp_path/'legacy'
    create_project(root, 'provenance_test', 'Generated machine', 'stage1_only', [task])
    manager = ManifestManager(root)
    manager.approve_plan()
    manager.set_delivery_target('asset')
    client, transport = gateway(glb_bytes)
    client.config['output_source'] = copy.deepcopy(SOURCE)
    result = Stage1Executor(manager, {provider.name: provider}, client).run('machine')
    assert result['source'] == SOURCE
    assert validate_result(root, result).read_bytes() == glb_bytes
    manager.review({'asset_id': 'machine', 'revision': 0, 'decision': 'approved',
                    'issues': [], 'instruction': '', 'reviewer': 'user'})
    delivered = cli('deliver', root)
    assert delivered.returncode == 0, delivered.stderr
    report = json.loads(delivered.stdout)
    assert report['attribution'] == [SOURCE]
    package = (root/report['files'][0]).parent
    assert load_data(package/'attribution.yaml') == {'sources': [SOURCE]}


@pytest.mark.parametrize('field,value', [('license_verified', False), ('provider', 'local_library'),
    ('asset_id', 'tencent/Hunyuan3D-2'), ('original_url', 'https://example.com/model'),
    ('attribution_required', False), ('modification_allowed', False), ('license', 'unknown'),
    ('provider', None), ('asset_id', None), ('original_url', None), ('license_verified', None)])
def test_invalid_output_provenance_rejects_before_inference(tmp_path, glb_bytes, field, value):
    manager = ready(tmp_path)
    client, transport = gateway(glb_bytes)
    source = copy.deepcopy(SOURCE)
    if value is None:
        source.pop(field)
    else:
        source[field] = value
    client.config['output_source'] = source
    before = manager.path.read_bytes()
    with pytest.raises(WorkflowError, match='rights'):
        executor(manager, client).run(generated_request())
    assert transport.calls == [] and manager.path.read_bytes() == before


@pytest.mark.parametrize('field,value', [('license_verified', False), ('provider', 'local_library'),
    ('asset_id', 'tencent/Hunyuan3D-2'), ('original_url', 'https://example.com/model'),
    ('attribution_required', False)])
def test_persisted_generated_result_rechecks_identity(tmp_path, glb_bytes, field, value):
    model = tmp_path/'stage1/outputs/machine/rev00/asset.glb'
    model.parent.mkdir(parents=True)
    model.write_bytes(glb_bytes)
    source = copy.deepcopy(SOURCE)
    source[field] = value
    result = {'asset_id': 'machine', 'revision': 0, 'route': 'hy3d_generate',
              'source': source, 'files': {'model': model.relative_to(tmp_path).as_posix()},
              'sha256': sha256(model), 'status': 'review_required', 'recipe': {}}
    with pytest.raises(WorkflowError, match='licens'):
        validate_result(tmp_path, result)


def test_library_metadata_cannot_activate_model_license(candidate):
    candidate['source'] = copy.deepcopy(SOURCE)
    assert not AssetRouter().legal(candidate)
    assert not AssetRouter().legal(candidate, modification=True)


@pytest.mark.parametrize('license_id', [[], {}])
def test_malformed_license_rejects_cleanly_before_generation(tmp_path, glb_bytes, license_id):
    manager = ready(tmp_path)
    client, transport = gateway(glb_bytes)
    source = copy.deepcopy(SOURCE)
    source['license'] = license_id
    client.config['output_source'] = source
    before = manager.path.read_bytes()
    with pytest.raises(WorkflowError, match='rights'):
        executor(manager, client).run(generated_request())
    assert transport.calls == [] and manager.path.read_bytes() == before


@pytest.mark.parametrize('license_id', [[], {}])
def test_malformed_license_leaves_legacy_failure_state(tmp_path, glb_bytes, provider, license_id):
    task = new_task('machine', 'unique machine')
    task['search']['keywords'] = ['unique machine']
    task['hy3d'].update(enabled=True, mode='shape')
    task['routing']['preferred_route'] = 'hy3d_generate'
    root = tmp_path/'legacy'
    create_project(root, 'provenance_test', 'Generated machine', 'stage1_only', [task])
    manager = ManifestManager(root)
    manager.approve_plan()
    client, transport = gateway(glb_bytes)
    client.config['output_source'] = copy.deepcopy(SOURCE)
    client.config['output_source']['license'] = license_id
    with pytest.raises(WorkflowError, match='rights'):
        Stage1Executor(manager, {provider.name: provider}, client).run('machine')
    assert transport.calls == []
    assert manager.read()['assets']['machine']['status'] == 'failed'


@pytest.mark.parametrize('license,verified,attribution,expected', [
    ('cc0', True, False, True), ('cc_by', True, True, True),
    ('cc_by', True, False, False), ('cc0', False, False, False),
    ('proprietary', True, True, False)])
def test_generic_license_defaults_remain(candidate, license, verified, attribution, expected):
    candidate['source'].update(license=license, license_verified=verified, attribution_required=attribution)
    assert AssetRouter().legal(candidate) is expected


@pytest.mark.parametrize('route', ['library_direct', 'library_hy3d_refine'])
def test_non_generated_result_cannot_claim_model_license(tmp_path, glb_bytes, route):
    model = tmp_path/'stage1/outputs/machine/rev00/asset.glb'
    model.parent.mkdir(parents=True)
    model.write_bytes(glb_bytes)
    result = {'asset_id': 'machine', 'revision': 0, 'route': route,
              'source': copy.deepcopy(SOURCE), 'files': {'model': model.relative_to(tmp_path).as_posix()},
              'sha256': sha256(model), 'status': 'review_required', 'recipe': {}}
    with pytest.raises(WorkflowError, match='licens'):
        validate_result(tmp_path, result)
